



typePrompt = """
  USER QUESTION: {question}

  The SQL Query:
  \`\`\`SQL
  {query}
  \`\`\`
  
  The query returned {res.rowCount} row(s) in total, here is table showing a sample of the first few rows:
  {makeTable(res, 3)}

  What is the most appropriate representation type to best represent this data, either as a simple sentence describing the results, as a table or as a chart ? Reply with either "sentence", "table" or "chart" and nothing more.
  
  Rules:
  - The type should either be "table", "sentence" or "chart"
  - If the user has specified the type in his question then use that
  - The type should not exceed one word

  Type:
"""

  if (DEBUG) console.log(typePrompt);

  messages.push({
    role: 'user',
    content: typePrompt,
  });

  completion = await openai.createChatCompletion({
    model: 'gpt-3.5-turbo',
    messages: messages,
  });

  const type = completion.data.choices[0].message?.content;
  messages.push(completion.data.choices[0].message);
  if (DEBUG) console.log(type);

  if (type == 'chart') {
    const chartObjectPrompt = `
The rows generated by the query are stored in a list format at \`res.rows\`

Generate the most appropriate chart using the chart.js library

Rules:
- The JS object should generate colors randomly for backgroundColors and other field about colors
- The JS object should be top level and structured as 
\`\`\`js
{
  type: string,
  data: {
   labels: list, // generate list dynamically from res.rows
   datasets: [{
     data: list, // generate list dynamically from res.rows
   }]
  },
  options: object, // asign options.title.text and others dynamically
}
\`\`\`
- This js object should be the sole content of the message, there should be no intermediate variables
- The JS object should make use of data from the \`res.rows\` object to handle labels, datasets, axes title and others
- The JS object should start with { and end with }
- The JS object should be syntaxically correct

JS Object:
`;

    messages.push({
      role: 'user',
      content: chartObjectPrompt,
    });

    completion = await openai.createChatCompletion({
      model: 'gpt-3.5-turbo',
      messages: messages,
    });

    if (DEBUG) console.log(completion.data.choices[0].message?.content);

    let chartObject: any = completion.data.choices[0].message?.content;

    chartObject = chartObject.replace('```js\n', '').replace(/```/g, '');

    messages.push(completion.data.choices[0].message);
    if (DEBUG) console.log(chartObject);

    const chart = ChartJSImage()
      .chart(eval(`(() => { return ${chartObject}; })()`)) // Line chart
      .backgroundColor('transparent')
      .width(800) // 500px
      .height(350); // 300px

    const image = await chart.toDataURI();

    return {
      data: res.rows,
      markdown: `## Chart\n![](${image})\n\n### Query\n\`\`\`SQL\n${query}\n\`\`\``,
    };
  }

  // Else
  else if (type == 'table') {
    return {
      data: res.rows,
      markdown: `## Table\n${makeTable(res, res.rowCount)}\n\n### Query\n\`\`\`SQL\n${query}\n\`\`\``,
    };
  } else {
    const sentencePrompt = `Using the previously given sample of results make a human-sounding sentence replying to the initial question which was: "${question}"
    
    The results should be highlighted in bold by adding ** around them.

    Sentence:
    `;

    messages.push({
      role: 'user',
      content: sentencePrompt,
    });

    completion = await openai.createChatCompletion({
      model: 'gpt-3.5-turbo',
      messages: messages,
    });

    const sentence = completion.data.choices[0].message?.content;
    messages.push(completion.data.choices[0].message);

    return {
      data: res.rows,
      markdown: `## Result\n ${sentence}\n\n### Query\n\`\`\`SQL\n${query}\n\`\`\``,
    };
  }
}
