from langchain.chat_models import ChatOpenAI
from langchain import OpenAI
import os
import sqlalchemy
from langchain.chains import LLMChain
from langchain.prompts.prompt import PromptTemplate
from schema import execute_query, get_schema_info
question = "what are the top 5 most sold items."

db_schema = get_schema_info()
PROMPT_SUFFIX = """
Below is the schema of the database. Only use the following tables and columns:
{DB_schema}

Question: {input}

Query:
"""

_postgres_prompt = """
You are a PostgreSQL expert. Given an input question, create a syntactically correct PostgreSQL query. 

With the following rules:
- The SQL Query should respect the case and consider columns and tables as case-sensitive
- The SQL Query should use quotes around table and column names containing uppercase characters
- The SQL Query should be syntaxically correct
- The SQL Query should be the sole content of your message
- Pay attention to use CURRENT_DATE function to get the current date, if the question involves "today"
- Pay attention to add table name in front of column name in the SELECT statement with the format "table_name.column_name
- Your response should be a PostgreSQL query and nothing else.
# """
POSTGRES_PROMPT = PromptTemplate(
            input_variables=["input", "DB_schema"],
            template=_postgres_prompt + PROMPT_SUFFIX,
        )
llm = ChatOpenAI(temperature=0.5, openai_api_key="", model='gpt-3.5-turbo')
chain = LLMChain(llm=llm, prompt=POSTGRES_PROMPT)

# Run the chain only specifying the input variable.
sql_query = chain.run({'input': question, 
                       'DB_schema': db_schema})

# sql_query = """
#         SELECT products.product_name, SUM(order_details.quantity) AS total_sold
#         FROM products
#         JOIN order_details ON products.product_id = order_details.product_id
#         GROUP BY products.product_name
#         ORDER BY total_sold DESC
#         LIMIT 5;
# """
print(sql_query)
result = execute_query(sql_query)

print(result)


def make_table(res, size=3):
    max_name_length = max(len(name) for name, _ in res)
    table_str = ""
    for i in range(size):
        
        if i >= len(res):
            break

        name, number = res[i]
        row = f"| {name:<{max_name_length}} | {number} |\n"
        table_str += row

    return table_str

total = len(result)
table = make_table(result)
typePrompt = """
This SQL Query: {query}
Returned {total} row(s) in total, here is table showing a sample of the first few rows: 
{table}

What is the most appropriate representation type to best represent this data, either as a simple sentence describing the results, as a table or as a chart? Reply with either "sentence", "table" or "chart" and nothing more.

Rules:
- The type should either be "table", "sentence" or "chart"
- The type should not exceed one word

Type:

  """



SELECTION_PROMPT = PromptTemplate(
            input_variables=["query", "total", "table"],
            template=typePrompt,
        )

chain = LLMChain(llm=llm, prompt=SELECTION_PROMPT)
type = chain.run({'query': sql_query,
                'total': total,
                'table': table})

res = [[name, number] for name, number in result]
if type == "chart":
    chartObjectPrompt = """
The {total} rows generated by the SQL query are stored in 'res'. The first three rows are: {res_}

Generate the most appropriate chart using the chart.js library

Rules:
- The JS object should generate colors randomly for backgroundColors and other field about colors
- The JS object should be top level and structured as 
\`\`\`js
{
type: string,
data: {
    labels: list, // generate list dynamically from res.map(([labels, _]) => labels)
    datasets: [{
        data: list, // generate list dynamically from res.map(([_, data]) => data)
    }]
},
options: object, // asign options.title.text and others dynamically
}
\`\`\`
- This js object should be the sole content of the message, there should be no intermediate variables
- The JS object should make use of data from the \`res.rows\` object to handle labels, datasets, axes title and others
- The JS object should start with { and end with }
- The JS object should be syntaxically correct

JS Object:
    `;
    """
    CHART_PROMPT = PromptTemplate(
            input_variables=["res_", "total"],
            template=chartObjectPrompt,
        )

    chain = LLMChain(llm=llm, prompt=CHART_PROMPT)
    chartObj = chain.run({'res_': res[:3],
                    'total': total})
    


elif type == "table":
    make_table(result, len(result))

else:
    sentencePrompt = """
    SQL query: {sql_query}  
    result: {result}
    Using the given result make a human-sounding sentence replying to the initial question which was: "{question}"
    
    The results should be highlighted in bold by adding ** around them.

    Sentence:
    `;
    """

    SENTENCE_PROMPT = PromptTemplate(
            input_variables=["sql_query", "result", "question"],
            template=sentencePrompt,
        )

    chain = LLMChain(llm=llm, prompt=SENTENCE_PROMPT)
    chartObj = chain.run({'sql_query': sql_query,
                    'result': result,
                    "question" : question})

