from langchain.chat_models import ChatOpenAI
from langchain import OpenAI
import os
import sqlalchemy
from langchain.chains import LLMChain
from langchain.prompts.prompt import PromptTemplate
from schema import execute_query, get_schema_info
from SQL_CHAIN import SQL_QUERY_PROMPT
import numpy as np
llm = ChatOpenAI(temperature=0.5, openai_api_key="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", model='gpt-3.5-turbo')
SQL_CHAIN = LLMChain(llm=llm, prompt=SQL_QUERY_PROMPT)

def make_table(res, size=1):
    max_name_length = max(len(name) for name, _ in res)
    table_str = ""
    for i in range(size):
        
        if i >= len(res):
            break

        name, number = res[i]
        row = f"| {name:<{max_name_length}} | {number} |\n"
        table_str += row

    return table_str

def chatbot(question):
    sql_query = SQL_CHAIN.run(question)
    result = execute_query(sql_query)
    total = len(result)
    table = make_table(result)
    typePrompt = """
        USER QUESTION: {question}
        This SQL Query: {query}
        Returned {total} row(s) in total, here is table showing a sample of the first row: 
        {table}

        What is the most appropriate representation type to best represent this data, either as a simple sentence describing the results, as a table or as a chart? Reply with either "sentence", "table" or "chart" and nothing more.

        Rules:
        - If the user has mentioned the type in the question then you must return that
        - The type should either be "table", "sentence" or "chart"
        - The type should not exceed one word

        Type:

        """
    SELECTION_PROMPT = PromptTemplate(
                input_variables=["question", "query", "total", "table"],
                template=typePrompt,
            )

    chain = LLMChain(llm=llm, prompt=SELECTION_PROMPT)
    type = chain.run({'question': question,
                    'query': sql_query,
                    'total': total,
                    'table': table})

    res = [[name, number] for name, number in result]


    if type == "chart":
        chartObjectPrompt = """
            USER QUESTION: {question}
            The {total} rows generated by the SQL query are stored in 'res'. The first few row are: {res_}. Shape of 'res': {shape}

            Generate the most appropriate chart using the chart.js library

            Rules:
            - If the user has sepecifies the type of chart then use that
            - The JS object should generate colors randomly for backgroundColors and other field about colors
            - The JS object should be top level and structured as 

            {{
                type: string,
                data: {{
                    labels: list, // generate list dynamically from res.map(([labels, _]) => labels)
                    datasets: [{{
                        data: list, // generate list dynamically from res.map(([_, data]) => data)
                    }}]
                }},
                options: object, -- asign options.title.text and others dynamically
            }}

            - This js object should be the sole content of the message, there should be no intermediate variables
            - The JS object should make use of data from the 'res.rows' object to handle labels, datasets, axes title and others
            - The JS object should start with '{{' and end with '}}'
            - The JS object should be syntaxically correct

            JS Object:

        """
        CHART_PROMPT = PromptTemplate(
                input_variables=["question", "total", "res_", "shape"],
                template=chartObjectPrompt,
            )
        
        chain = LLMChain(llm=llm, prompt=CHART_PROMPT)
        np_res = np.array(res)
        shape = np_res.shape
        chartObj = chain.run({'question' : question,
                            'total': total, 
                            'res_': res[:1],
                            'shape': shape})
        


    elif type == "table":
        chartObj = make_table(result, len(result))

    else:
        sentencePrompt = """
            SQL query: {sql_query}  
            result: {result}
            Using the given result make a human-sounding sentence replying to the initial question which was: "{question}"
            
            The results should be highlighted in bold by adding ** around them.

            Sentence:
            `;
            """

        SENTENCE_PROMPT = PromptTemplate(
                input_variables=["sql_query", "result", "question"],
                template=sentencePrompt,
            )

        chain = LLMChain(llm=llm, prompt=SENTENCE_PROMPT)
        chartObj = chain.run({'sql_query': sql_query,
                        'result': result,
                        "question" : question})

    return {'SQL_QUERY': sql_query, 'DATA': result, 'TYPE': type, 'CHART': chartObj}